services:
  api:
    build: ./api
    ports:
      - "8000:8000"
  base:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: clase3
  broker:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
       